name: render_box_exposed
description: A flutter package to expose a widget's RenderBox
version: 1.0.0
homepage: https://github.com/SBTopZZZ-LG/flutter_render_box_exposed

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
